select * from SUPER_USER.PRIVATE_POSTS;
select * from SUPER_USER.TOP_3_USERS_MAX_POSTS;
select * from SUPER_USER.POSTS_BETWEEN;
select * from SUPER_USER.MAX_COMMENTS;
select * from SUPER_USER.NO_CONNECTION_USERS;
SELECT * FROM SUPER_USER.USER_TIMELINE WHERE FOLLOWER_ID = 78;